=== ChihabMakkoudi/MonumentBackEnd/src/main/resources/templates/Monument.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Monument">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:string" />
                <xs:element name="nom" type="xs:string" />
                <xs:element name="description" type="xs:string" />
                <xs:element name="coordinate">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="latitude" type="xs:string" />
                            <xs:element name="longitude" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="liensImage">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="liensImage" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ville">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string" />
                            <xs:element name="description" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="evaluations" />
                <xs:element name="rating" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ChihabMakkoudi/MonumentBackEnd/monuments/236.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>236</id>
   <nom>Fabrica de alfombras artesanales</nom>
   <description>Douar Ihrtan, Tinerhir Morocco</description>
   <coordinate>
      <latitude>30.3907</latitude>
      <longitude>-9.52142</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-w/1a/12/e1/98/tapis-berbere.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Tinerhir</nom>
      <description>Tinerhir</description>
   </ville>
   <evaluations/>
   <rating>4.5</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/271.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>271</id>
   <nom>Medina of Tetouan</nom>
   <description>Tetouan Morocco</description>
   <coordinate>
      <latitude>35.58817</latitude>
      <longitude>-5.362774</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/12/60/bc/11/cartoline-da-tetouan.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Tetouan</nom>
      <description>Tetouan</description>
   </ville>
   <evaluations/>
   <rating>4.0</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/117.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>117</id>
   <nom>Mellah</nom>
   <description>Marrakech Morocco</description>
   <coordinate>
      <latitude>31.619566</latitude>
      <longitude>-7.982503</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/0f/11/05/8f/auf-dem-sehr-grossen.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Marrakech</nom>
      <description>Marrakech</description>
   </ville>
   <evaluations/>
   <rating>4.0</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/154.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>154</id>
   <nom>Heri es Souani</nom>
   <description>Meknes Morocco</description>
   <coordinate>
      <latitude>33.880245</latitude>
      <longitude>-5.557978</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/0d/c3/f3/a1/granary.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Meknes</nom>
      <description>Meknes</description>
   </ville>
   <evaluations/>
   <rating>4.0</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/90.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>90</id>
   <nom>Tanneries of Tetouan</nom>
   <description>Rue Laayoun close to Bab Mkabar, Tetouan Morocco</description>
   <coordinate>
      <latitude>35.75073</latitude>
      <longitude>-5.82909</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-w/17/31/cc/83/tanneries-of-tetouan.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Tetouan</nom>
      <description>Tetouan</description>
   </ville>
   <evaluations/>
   <rating>4.5</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/47.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>47</id>
   <nom>Borj Nord</nom>
   <description>Avenue des Merinides, Fes 30030 Morocco</description>
   <coordinate>
      <latitude>34.07234</latitude>
      <longitude>-4.98142</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-m/1280/16/2a/90/01/borj-nord.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Fes</nom>
      <description>Fes</description>
   </ville>
   <evaluations/>
   <rating>4.0</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/282.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>282</id>
   <nom>Hammam Torgan Hommes</nom>
   <description>Hjar Laaroussa N20 Route De Sebta Pres De Hotel, Tetouan 93000 Morocco</description>
   <coordinate>
      <latitude>35.565826</latitude>
      <longitude>-5.360555</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/1d/81/9a/6c/caption.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Tetouan</nom>
      <description>Tetouan</description>
   </ville>
   <evaluations/>
   <rating>4.5</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/185.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>185</id>
   <nom>Jimmy's Fitness Center</nom>
   <description>38 Avenue Hassan Ii Résidence « Royale »,, Kenitra 14000 Morocco</description>
   <coordinate>
      <latitude>34.259106</latitude>
      <longitude>-6.580966</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/1d/71/47/5d/accueil.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Kenitra</nom>
      <description>Kenitra</description>
   </ville>
   <evaluations/>
   <rating>5.0</rating>
</Monument>
