=== ChihabMakkoudi/MonumentBackEnd/src/main/resources/templates/Monument.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Monument">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:string" />
                <xs:element name="nom" type="xs:string" />
                <xs:element name="description" type="xs:string" />
                <xs:element name="coordinate">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="latitude" type="xs:string" />
                            <xs:element name="longitude" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="liensImage">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="liensImage" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ville">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string" />
                            <xs:element name="description" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="evaluations" />
                <xs:element name="rating" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ChihabMakkoudi/MonumentBackEnd/monuments/7.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>7</id>
   <nom>The Corniche</nom>
   <description>Boulevard de la Corniche, Casablanca 20000 Morocco</description>
   <coordinate>
      <latitude>33.596264</latitude>
      <longitude>-7.674186</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/0e/35/43/93/schones-restaurant.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Casablanca</nom>
      <description>Casablanca</description>
   </ville>
   <evaluations/>
   <rating>4.0</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/132.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>132</id>
   <nom>Plage de Rabat</nom>
   <description>Rabat Morocco</description>
   <coordinate>
      <latitude>34.032967</latitude>
      <longitude>-6.835805</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/11/ec/4d/3c/img-20180127-132337802.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Rabat</nom>
      <description>Rabat</description>
   </ville>
   <evaluations/>
   <rating>3.0</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/174.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>174</id>
   <nom>Dome Sir Son Isa</nom>
   <description>Meknes Morocco</description>
   <coordinate>
      <latitude>33.89913</latitude>
      <longitude>-5.570492</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-m/1280/1b/33/f3/b9/dome-sir-son-isa.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Meknes</nom>
      <description>Meknes</description>
   </ville>
   <evaluations/>
   <rating>3.0</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/273.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>273</id>
   <nom>Modern Art Center of Tetouan</nom>
   <description>S/N, Avenue Al Massira, Tetouan 93000 Morocco</description>
   <coordinate>
      <latitude>35.57693</latitude>
      <longitude>-5.37273</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/06/80/74/04/the-tetouan-centre-of.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Tetouan</nom>
      <description>Tetouan</description>
   </ville>
   <evaluations/>
   <rating>4.0</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/39.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>39</id>
   <nom>Kairaouine Mosque (Mosque of al-Qarawiyyin)</nom>
   <description>Fes el-Bali Qayruwan quarters, Fes 30030 Morocco</description>
   <coordinate>
      <latitude>34.064938</latitude>
      <longitude>-4.973366</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-m/1280/16/47/5a/8f/photo1jpg.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Fes</nom>
      <description>Fes</description>
   </ville>
   <evaluations/>
   <rating>4.0</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/303.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>303</id>
   <nom>Laayoune Off Road</nom>
   <description>Akhfennir Centre Akhfennir, Laayoune 70072 Morocco</description>
   <coordinate>
      <latitude>27.14855</latitude>
      <longitude>-13.1963</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/03/61/79/e8/getlstd-property-photo.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Laayoune</nom>
      <description>Laayoune</description>
   </ville>
   <evaluations/>
   <rating>5.0</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/50.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>50</id>
   <nom>Palais El Mokri</nom>
   <description>34, Palais Elmokri, Ziat, Fes 30000 Morocco</description>
   <coordinate>
      <latitude>34.04199</latitude>
      <longitude>-5.00867</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/13/c6/6e/30/20180617-132857-largejpg.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Fes</nom>
      <description>Fes</description>
   </ville>
   <evaluations/>
   <rating>4.5</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/105.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>105</id>
   <nom>Marrakech Train Station</nom>
   <description>Hasan II Avenue, Marrakech 40050 Morocco</description>
   <coordinate>
      <latitude>31.63376</latitude>
      <longitude>-8.0021</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/07/67/25/6d/station-marrakesh.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Marrakech</nom>
      <description>Marrakech</description>
   </ville>
   <evaluations/>
   <rating>4.5</rating>
</Monument>
