=== ChihabMakkoudi/MonumentBackEnd/src/main/resources/templates/Monument.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Monument">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:string" />
                <xs:element name="nom" type="xs:string" />
                <xs:element name="description" type="xs:string" />
                <xs:element name="coordinate">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="latitude" type="xs:string" />
                            <xs:element name="longitude" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="liensImage">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="liensImage" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ville">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string" />
                            <xs:element name="description" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="evaluations" />
                <xs:element name="rating" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ChihabMakkoudi/MonumentBackEnd/monuments/60.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>60</id>
   <nom>La Belle Vue de la Tannerie</nom>
   <description>64 Derb Sidi Bouaza, Fes Morocco</description>
   <coordinate>
      <latitude>34.06676</latitude>
      <longitude>-4.97104</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/1b/5e/dd/82/la-belle-vue-de-la-tannerie.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Fes</nom>
      <description>Fes</description>
   </ville>
   <evaluations/>
   <rating>4.0</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>2</id>
   <nom>ONCF</nom>
   <description>Marrakech Morocco</description>
   <coordinate>
      <latitude>33.59016</latitude>
      <longitude>-7.590017</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/09/f9/e1/83/oncf.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Marrakech</nom>
      <description>Marrakech</description>
   </ville>
   <evaluations/>
   <rating>3.0</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/366.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>366</id>
   <nom>Grand Mosque</nom>
   <description>Plaza Uta el-Hammam, Chefchaouen 91000 Morocco</description>
   <coordinate>
      <latitude>35.16738</latitude>
      <longitude>-5.26185</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/11/4d/6c/05/img-20171116-145345-largejpg.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Chefchaouen</nom>
      <description>Chefchaouen</description>
   </ville>
   <evaluations/>
   <rating>4.0</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/63.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>63</id>
   <nom>Tangier Casbah</nom>
   <description>Place de la Kasbah, Tangier 90000 Morocco</description>
   <coordinate>
      <latitude>35.75073</latitude>
      <longitude>-5.82909</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/17/10/b1/d4/tangier-casbah.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Tangier</nom>
      <description>Tangier</description>
   </ville>
   <evaluations/>
   <rating>4.0</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/135.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>135</id>
   <nom>La Villa des Arts</nom>
   <description>10 Rue Beni Mellal, Angle Avenue, Rabat 10030 Morocco</description>
   <coordinate>
      <latitude>34.01272</latitude>
      <longitude>-6.830622</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/0b/7e/45/3b/villa-des-arts-front.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Rabat</nom>
      <description>Rabat</description>
   </ville>
   <evaluations/>
   <rating>4.5</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/68.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>68</id>
   <nom>Feddan Park Tetouan</nom>
   <description>Avenue Alger, Tetouan Morocco</description>
   <coordinate>
      <latitude>35.77443</latitude>
      <longitude>-5.80819</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-m/1280/15/04/bb/07/feddan-park-tetouan.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Tetouan</nom>
      <description>Tetouan</description>
   </ville>
   <evaluations/>
   <rating>4.5</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/52.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>52</id>
   <nom>Dar Batha Museum</nom>
   <description>Place du Batha Fez, Fes 30030 Morocco</description>
   <coordinate>
      <latitude>34.060474</latitude>
      <longitude>-4.98324</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/0a/52/d0/de/photo2jpg.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Fes</nom>
      <description>Fes</description>
   </ville>
   <evaluations/>
   <rating>3.5</rating>
</Monument>

=== ChihabMakkoudi/MonumentBackEnd/monuments/228.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="../src/main/resources/templates/Monument.xsd">
   <id>228</id>
   <nom>Memoire d'Agadir</nom>
   <description>Ave du President Kennedy &amp; Ave des Far, Agadir Morocco</description>
   <coordinate>
      <latitude>30.424723</latitude>
      <longitude>-9.598011</longitude>
   </coordinate>
   <liensImage>
      <liensImage>https://media-cdn.tripadvisor.com/media/photo-o/0a/66/59/af/photo1jpg.jpg</liensImage>
   </liensImage>
   <ville>
      <nom>Agadir</nom>
      <description>Agadir</description>
   </ville>
   <evaluations/>
   <rating>4.0</rating>
</Monument>
